[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  functions = "netlify/functions"
  publish = "build"

[functions]
  node_bundler = "esbuild"
  
  [functions.node_version]
  version = "16"
